/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author c.denys
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SInscrire = new javax.swing.JButton();
        SeConnecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("WebCaisse");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 100, 130, 28);

        SInscrire.setText("S'inscrire");
        SInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SInscrireActionPerformed(evt);
            }
        });
        getContentPane().add(SInscrire);
        SInscrire.setBounds(230, 230, 230, 30);

        SeConnecter.setText("Se connecter");
        SeConnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeConnecterMouseClicked(evt);
            }
        });
        SeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeConnecterActionPerformed(evt);
            }
        });
        getContentPane().add(SeConnecter);
        SeConnecter.setBounds(230, 180, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SInscrireActionPerformed
        // Créer une instance de la fenêtre "Inscription"
        Inscription inscription = new Inscription();

        // Afficher la nouvelle fenêtre
        inscription.setVisible(true);

        // Cacher la fenêtre "Accueil"
        this.setVisible(false);
    }//GEN-LAST:event_SInscrireActionPerformed

    private void SeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeConnecterActionPerformed
        // Créer une instance de la fenêtre "Connection"
        Connection connection = new Connection();

        // Afficher la nouvelle fenêtre
        connection.setVisible(true);

        // Cacher la fenêtre "Accueil"
        this.setVisible(false);
    }//GEN-LAST:event_SeConnecterActionPerformed

    private void SeConnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeConnecterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SeConnecterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SInscrire;
    private javax.swing.JButton SeConnecter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
