/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Client;

/**
 *
 * @author c.denys
 */
public class AccueilPostLogin extends javax.swing.JFrame {

    /**
     * Creates new form accueil
     */
    
    private Client client;
    
    public AccueilPostLogin(Client client) {
        this.client = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        GestionPointsDeVente = new javax.swing.JButton();
        UserName = new javax.swing.JLabel();
        AjoutPointDeVente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextPane1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas congue non libero et ultrices. Cras faucibus euismod augue. Aliquam sit amet placerat elit. Aliquam ex arcu, iaculis at ex sed, semper tincidunt lorem. Aliquam placerat neque justo, nec auctor ex maximus id. Fusce eu bibendum justo. Fusce ac est vitae odio congue elementum eu dictum ante. Nam ac eros at odio consequat egestas ac eu mi. Sed gravida elit et ex interdum, ut accumsan nisi eleifend. Duis et tellus scelerisque, dictum nulla eu, volutpat dui. Donec massa odio, aliquet in ornare a, pharetra placerat arcu. Vestibulum tristique vulputate eros eu porta. Integer sed viverra nunc, et auctor dui. Phasellus posuere quam ut justo viverra, quis pharetra ligula varius.\n\nNunc sit amet lectus turpis. Suspendisse tincidunt vitae nulla id consequat. Morbi laoreet eleifend nulla at blandit. Sed vulputate aliquam erat, sit amet placerat mi. Sed eget ornare ex. Integer tristique purus ut tellus consectetur, id dapibus lacus fermentum. Quisque vestibulum elit elit, interdum semper est gravida in. Ut tortor turpis, porta eu placerat quis, sollicitudin malesuada felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum auctor dui lectus, id congue orci dapibus sit amet. In condimentum lorem eget orci luctus, euismod iaculis nisi tristique. Duis id congue orci. Sed pharetra nulla eu metus sollicitudin, vitae consectetur sem blandit. Sed at enim suscipit, lobortis nunc in, sollicitudin est. Proin mollis lectus a tortor condimentum pulvinar.");
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 680, 390);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Accueil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 90, 28);

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Logout.setText("Se déconnecter");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout);
        Logout.setBounds(50, 40, 110, 20);

        GestionPointsDeVente.setText("Gérer mes points de vente");
        GestionPointsDeVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionPointsDeVenteActionPerformed(evt);
            }
        });
        getContentPane().add(GestionPointsDeVente);
        GestionPointsDeVente.setBounds(450, 20, 230, 30);

        UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserName.setText(client.getNom() + " " + client.getPrenom());
        getContentPane().add(UserName);
        UserName.setBounds(50, 20, 110, 16);

        AjoutPointDeVente.setText("Ajouter un point de vente");
        AjoutPointDeVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutPointDeVenteActionPerformed(evt);
            }
        });
        getContentPane().add(AjoutPointDeVente);
        AjoutPointDeVente.setBounds(210, 20, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        client = null;
        Accueil accueil = new Accueil();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void GestionPointsDeVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionPointsDeVenteActionPerformed
        GestionPointsDeVente gestionPointsDeVente = new GestionPointsDeVente(client);
        gestionPointsDeVente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GestionPointsDeVenteActionPerformed

    private void AjoutPointDeVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutPointDeVenteActionPerformed
        AjoutPointDeVente ajoutPointDeVente = new AjoutPointDeVente(client);
        ajoutPointDeVente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AjoutPointDeVenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilPostLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilPostLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilPostLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilPostLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Client client) {
                new AccueilPostLogin(client).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutPointDeVente;
    private javax.swing.JButton GestionPointsDeVente;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
